<?php 


use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Form\FormStateInterface;


function custom_module_theme($existing, $type, $theme, $path) {
		$module_path = drupal_get_path('module','custom_module');
  return array(
    'block_copyright' => array(
     'path' => $module_path . '/templates',
     'template' => 'block--copyright',
     'variables' => ['abc' => null],
    ),
  );
}
function custom_module_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_login_block') {
    print_r($form['links']);exit();
    unset($form['links']);
  }
}