<?php 


use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Form\FormStateInterface;


function custom_module_theme($existing, $type, $theme, $path) {
		$module_path = drupal_get_path('module','custom_module');
  return array(
    'block_copyright' => array(
     'path' => $module_path . '/templates',
     'template' => 'block--copyright',
     'variables' => ['abc' => null],
    ),
  );
}


function custom_module_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
    if ($form_id == 'user_login_form') {
    $form['actions']['submit']['#value'] = t('SIGN IN');
  }

  if ($form_id == 'user_register_form') {
    $form['account']['mail']['#required'] = FALSE;
    unset($form['account']['mail']);
    $form['account']['pass']['#type'] = 'password';
    $form['account']['pass']['#type'] = 'password';
    $form['account']['pass']['#title'] = 'Password'; 
    $form['actions']['submit']['#value'] = t('CREATE ACCOUNT');
  }
}
  
/**
* Implements hook_preprocess_page(&$variables)
*/
function custom_module_preprocess_page(&$variables) {
  if (\Drupal::service('path.matcher')->isFrontPage() == 1) {
    $variables['#attached']['library'][] = 'srm/slick';
  }
}
