commerce_quickpay_gateway.commerce_payment_gateway.plugin.quickpay_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    private_key:
      type: string
      label: 'Private key'
    agreement_id:
      type: string
      label: 'Agreement ID'
    api_key:
      type: string
      label: 'API key'
    order_prefix:
      type: string
      label: 'Order ID prefix'
    language:
      type: string
      label: 'Language'
    payment_method:
      type: string
      label: 'Accepted payment methods'
    accepted_cards:
      type: string
      label: 'Selected accepted cards'
    autofee:
      type: boolean
      label: 'Autofee'
    autocapture:
      type: boolean
      label: 'Autocapture'
